services:

  epub2md:
    container_name: epub2md
    build:
      context: ./src/epub2md
      dockerfile: Dockerfile
    volumes:
      - ./.input:/.input
      - ./.output:/.output
      - ./src/epub2md/convert.sh:/usr/local/bin/convert.sh
    environment:
      - INPUT_DIR=/.input
      - OUTPUT_DIR=/.output

  pdf2md:
    container_name: pdf2md
    build:
      context: ./markitdown
      dockerfile: Dockerfile
    image: markitdown:latest
    volumes:
      - ./.input:/.input
      - ./.output:/.output
      - ./src/pdf2md/convert.sh:/convert.sh
    working_dir: /.input
    stdin_open: true
    tty: false
    entrypoint: /bin/sh
    command: ["-c", "tr -d '\\r' < /convert.sh | sh"]
